"""modify table

Revision ID: 30f5ee549e69
Revises: b3bb43707c88
Create Date: 2023-08-10 00:48:18.452450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f5ee549e69'
down_revision = 'b3bb43707c88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
