"""remove m2m connect

Revision ID: 3ebdbb9e0238
Revises: 75418133051d
Create Date: 2023-08-11 21:21:39.769669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ebdbb9e0238'
down_revision = '75418133051d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
