"""create blog and category table

Revision ID: 699c7e0986d7
Revises: 98515d4bbf08
Create Date: 2023-08-10 23:16:14.853837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699c7e0986d7'
down_revision = '98515d4bbf08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
