"""modify table

Revision ID: b3bb43707c88
Revises: 20f4374b1d12
Create Date: 2023-08-10 00:46:37.229535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3bb43707c88'
down_revision = '20f4374b1d12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
