"""change connection

Revision ID: dc751b363f86
Revises: 15943538ca0f
Create Date: 2023-08-11 13:53:15.135583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc751b363f86'
down_revision = '15943538ca0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blogs_category_id_fkey', 'blogs', type_='foreignkey')
    op.create_foreign_key(None, 'blogs', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.create_foreign_key('blogs_category_id_fkey', 'blogs', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
