"""modify table

Revision ID: f277fe3b1b34
Revises: 30f5ee549e69
Create Date: 2023-08-10 00:49:15.656139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f277fe3b1b34'
down_revision = '30f5ee549e69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
